name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - 5.3.x
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  ci:
    name: 'Nadav'
    runs-on: ${{ matrix.os.id }}
    timeout-minutes: 60
    if: ${{ github.repository == 'spring-projects/spring-framework' }}
    strategy:
      matrix:
        os:
          - id: ubuntu-latest
            name: Linux
        java:
          - version: 8
            toolchain: false
          - version: 17
            toolchain: true
          - version: 21
            toolchain: true
        exclude:
          - os:
              name: Linux
            java:
              version: 8
    steps:
      - name: Prepare Windows runner
        if: ${{ runner.os == 'Windows' }}
        run: |
          git config --global core.autocrlf true
          git config --global core.longPaths true
          Stop-Service -name Docker
      - name: Check Out Code
        uses: actions/checkout@v4
      - name: Build
        id: build
        uses: ./.github/actions/build
        with:
          java-version: ${{ matrix.java.version }}
          java-early-access: ${{ matrix.java.early-access || 'false' }}
          java-toolchain: ${{ matrix.java.toolchain }}
          develocity-access-key: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
